---
- name: Include distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - apt_sources

- name: Determine apt version
  command: dpkg-query --showformat='${Version}' --show apt
  changed_when: false
  register: apt_version
  tags:
    - apt_sources

- name: Install apt-transport-https
  become: true
  apt:
    name: apt-transport-https
    update_cache: true
  when: apt_version.stdout is version('1.5', '<')
  tags:
    - apt_sources
    - apt_sources_install

- name: Update sources.list file
  become: true
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
  register: update_sources_list
  tags:
    - apt_sources
    - apt_sources_configure

- name: Update apt cache
  become: true
  apt:
    update_cache: true
  when: update_sources_list.changed
  tags:
    - apt_sources
    - apt_sources_update_cache
