---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint -s . && ansible-lint . && flake8
platforms:
  - name: "instance"
    image: "${IMAGE:-geerlingguy/docker-ubuntu2004-ansible}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
